apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  namespace: web-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: poi        
        image: registryiwn0369.azurecr.io/tripinsights/poi
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        ports:
        - containerPort: 80
          name: poi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: keyvault
          nodePublishSecretRef:
              name: secrets-store-creds 
---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: web-apis
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: poi

