apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: web-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryiwn0369.azurecr.io/userprofile/userprofileapi
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        ports:
        - containerPort: 80
          name: userprofile
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: keyvault
          nodePublishSecretRef:
              name: secrets-store-creds 
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: web-apis
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: userprofile