apiVersion: apps/v1
kind: Deployment
metadata:
  name: userprofile
  namespace: web-apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userprofile
  template:
    metadata:
      labels:
        app: userprofile
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: userprofile
        image: registryiwn0369.azurecr.io/userprofile/userprofileapi
        ports:
        - containerPort: 80
          name: userprofile
        env:
        - name: SQL_USER
          value: "sqladminiWn0369"
        - name: SQL_PASSWORD
          value: "zM1lt3Gi7"
        - name: SQL_SERVER
          value: "sqlserveriwn0369.database.windows.net"
---
apiVersion: v1
kind: Service
metadata:
  name: userprofile
  namespace: web-apis
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: userprofile