apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: trips
        image: registryiwn0369.azurecr.io/tripinsights/trips
        ports:
        - containerPort: 80
          name: trips
        env:
        - name: SQL_USER
          value: "sqladminiWn0369"
        - name: SQL_PASSWORD
          value: "zM1lt3Gi7"
        - name: SQL_SERVER
          value: "sqlserveriwn0369.database.windows.net"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: trips